<?php

namespace App\Filament\Resources;

use App\Filament\Resources\DatabaseResource\Pages;
use App\Models\Database;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Placeholder;
use Filament\Forms\Components\Section;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Model;

class DatabaseResource extends Resource
{
    protected static ?string $model = Database::class;

    protected static ?string $slug = 'databases';

    protected static ?string $recordTitleAttribute = 'name';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Select::make('user.name')
                    ->relationship('user', 'name')
                    ->default(auth()->user()->id)->disabled(),

                Select::make('team.name')
                    ->relationship('team', 'name')
                    ->default(auth()->user()->current_team_id)->disabled(),

                TextInput::make('host')
                    ->required(),

                TextInput::make('port')
                    ->label('Port Number')
                    ->default(3306)
                    ->required()
                    ->integer(),

                TextInput::make('username')
                    ->required(),

                TextInput::make('password')->password(),

                TextInput::make('name')
                    ->label('Database Name')
                    ->required(),

                Section::make( 'Auto generated fields')
                    ->columns(3)
                    ->schema([
                            Placeholder::make('connected_at')
                                ->label('Last Connected Date')
                                ->content(fn(?Database $record): string => $record?->connected_at?->diffForHumans() ?? '-'),

                            Placeholder::make('created_at')
                                ->label('Created Date')
                                ->content(fn(?Database $record): string => $record?->created_at?->diffForHumans() ?? '-'),

                            Placeholder::make('updated_at')
                                ->label('Last Modified Date')
                                ->content(fn(?Database $record): string => $record?->updated_at?->diffForHumans() ?? '-'),
                    ]),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('user.name'),

                TextColumn::make('team.name'),

                TextColumn::make('host'),

                TextColumn::make('port'),

                TextColumn::make('username'),

                TextColumn::make('name')
                    ->searchable()
                    ->sortable(),

                TextColumn::make('connected_at')
                    ->label('Last Connected Date')
                    ->date(),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListDatabases::route('/'),
            'create' => Pages\CreateDatabase::route('/create'),
            'edit' => Pages\EditDatabase::route('/{record}/edit'),
        ];
    }

    public static function getGloballySearchableAttributes(): array
    {
        return ['name'];
    }

    public static function canCreate(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    public static function canDelete(Model $record): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

}
